# Generated by Django 2.1.1 on 2018-10-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('medida', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('pricesale', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('fechaElab', models.DateTimeField()),
                ('FechaExp', models.DateTimeField()),
                ('Estado', models.IntegerField()),
            ],
        ),
    ]
